zookeeper:
  config:
    clientPort: 2181

confluent:
  package_name: confluent-platform-2.11
  repository:
    debian:
    redhat:
      main:
        baseurl: https://packages.confluent.io/rpm/4.1/7
        gpgcheck: 0
        gpgkey: https://packages.confluent.io/rpm/4.1/archive.key
        enabled: 1
      dist:
        baseurl: https://packages.confluent.io/rpm/4.1/7
        gpgcheck: 0
        gpgkey:  https://packages.confluent.io/rpm/4.1/archive.key
        enabled: 1

