- import_role:
    name: connect
- name: connect standalone create log dir
  file:
    path: "{{kafka.connect.standalone.data_dir}}"
    state: directory
    mode: 0750
    owner: "{{kafka.connect.user}}"
    group: "{{kafka.connect.group}}"
- name: connect standalone create data dir
  file:
    path: "{{kafka.connect.standalone.environment.LOG_DIR}}"
    state: directory
    mode: 0750
    owner: "{{kafka.connect.user}}"
    group: "{{kafka.connect.group}}"
- name: connect standalone plugin path
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: "{{kafka.connect.user}}"
    group: "{{kafka.connect.group}}"
  with_items: "{{kafka.connect.standalone.plugin_path}}"
#- name: connect standalone create systemd unit
#  template:
#    src: connect-standalone.service.j2
#    dest: "{{kafka.connect.standalone.systemd_file}}"
#    mode: 0640
#    owner: "{{kafka.connect.user}}"
#    group: "{{kafka.connect.group}}"
#  notify:
#    - reload systemd
#    - restart connect standalone
- name: connect standalone create config
  template:
    src: connect-standalone.properties.j2
    dest: "{{kafka.connect.standalone.config_file}}"
    mode: 0640
    owner: "{{kafka.connect.user}}"
    group: "{{kafka.connect.group}}"
  notify:
    - restart connect standalone
- name: connect standalone configure service
  systemd:
    name: "{{kafka.connect.standalone.service_name}}"
    enabled: "{{kafka.connect.standalone.systemd.enabled}}"
    state: "{{kafka.connect.standalone.systemd.state}}"    
