- name: schema-registry create group
  group:
    name: "{{schema.registry.group}}"
- name: schema-registry create user
  user:
    name: "{{schema.registry.user}}"
    comment: "Zookeeper User"
    system: yes
    group: "{{schema.registry.group}}"
- name: schema-registry create log dir
  file:
    path: "{{schema.registry.environment.LOG_DIR}}"
    state: directory
    mode: 0750
    owner: "{{schema.registry.user}}"
    group: "{{schema.registry.group}}"
#- name: schema-registry create systemd unit
#  template:
#    src: schema-registry.service.j2
#    dest: "{{schema.registry.systemd_file}}"
#    mode: 0640
#    owner: root
#    group: root
#  notify:
#    - reload systemd
#    - restart schema-registry
- name: schema-registry create config
  template:
    src: schema-registry.properties.j2
    dest: "{{schema.registry.config_file}}"
    mode: 0640
    owner: "{{schema.registry.user}}"
    group: "{{schema.registry.group}}"
  notify:
    - restart schema-registry
- name: schema-registry configure service
  systemd:
    name: "{{schema.registry.service_name}}"
    enabled: "{{schema.registry.systemd.enabled}}"
    state: "{{schema.registry.systemd.state}}"
