schema:
  registry:
    user: cp-schema-registry
    group: confluent
    config_file: /etc/kafka/schema-registry.properties
    logging_config_file: /etc/kafka/schema-registry.logging.properties
    #    systemd_file: /usr/lib/systemd/system/confluent-schema-registry.service
    service_name: confluent-schema-registry
    config:
      listeners: http://0.0.0.0:8081
      kafkastore.topic: _schemas
      debug: false
    environment:
      SCHEMA_REGISTRY_HEAP_OPTS: "-Xmx1000M"
      LOG_DIR: /var/log/schema-registry
    systemd:
      enabled: yes
      state: started
      LimitNOFILE: 128000
      TimeoutStopSec: 300
      RestartSec: 5
