- name: connect distributed create log dir
  file:
    path: "{{kafka.connect.distributed.environment.LOG_DIR}}"
    state: directory
    mode: 0750
    owner: "{{kafka.connect.user}}"
    group: "{{kafka.connect.group}}"
#- name: connect distributed create systemd unit
#  template:
#    src: connect-distributed.service.j2
#    dest: "{{kafka.connect.distributed.systemd_file}}"
#    mode: 0600
#    owner: root
#    group: root
#  notify:
#    - reload systemd
#    - restart connect distributed
- name: connect distributed plugin path
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: "{{kafka.connect.user}}"
    group: "{{kafka.connect.group}}"
  with_items: "{{kafka.connect.distributed.plugin_path}}"
- name: connect distributed create config
  template:
    src: connect-distributed.properties.j2
    dest: "{{kafka.connect.distributed.config_file}}"
    mode: 0640
    owner: "{{kafka.connect.user}}"
    group: "{{kafka.connect.group}}"
  notify:
    - restart connect distributed
- name: connect distributed configure service
  systemd:
    name: "{{kafka.connect.distributed.service_name}}"
    enabled: "{{kafka.connect.distributed.systemd.enabled}}"
    state: "{{kafka.connect.distributed.systemd.state}}"    
