- name: kafka-rest create group
  group:
    name: "{{kafka.rest.group}}"
- name: kafka-rest create user
  user:
    name: "{{kafka.rest.user}}"
    comment: "Zookeeper User"
    system: yes
    group: "{{kafka.rest.group}}"
- name: kafka-rest create log dir
  file:
    path: "{{kafka.rest.environment.LOG_DIR}}"
    state: directory
    mode: 0750
    owner: "{{kafka.rest.user}}"
    group: "{{kafka.rest.group}}"
#- name: kafka-rest create systemd unit
#  template:
#    src: kafka-rest.service.j2
#    dest: "{{kafka.rest.systemd_file}}"
#    mode: 0600
#    owner: root
#    group: root
#  notify:
#    - reload systemd
#    - restart kafka-rest
- name: kafka-rest create config
  template:
    src: kafka-rest.properties.j2
    dest: "{{kafka.rest.config_file}}"
    mode: 0640
    owner: "{{kafka.rest.user}}"
    group: "{{kafka.rest.group}}"
  notify:
    - restart kafka-rest
- name: kafka-rest configure service
  systemd:
    name: "{{kafka.rest.service_name}}"
    enabled: "{{kafka.rest.systemd.enabled}}"
    state: "{{kafka.rest.systemd.state}}"
