confluent:
  control:
    center:
      user: cp-control-center
      group: confluent
      config_file: /etc/confluent-control-center/control-center.properties
      logging_config_file: /etc/confluent-control-center/zookeeper.logging.properties
      #      systemd_file: /usr/lib/systemd/system/confluent-control-center.service
      service_name: confluent-control-center
      data_dir: /var/lib/confluent-control-center
      tmp_dir: /var/lib/confluent-control-center/tmp
      config:
        confluent.controlcenter.streams.num.stream.threads: 8
      environment:
        CONTROL_CENTER_HEAP_OPTS: "-Xmx1000M"
        LOG_DIR: /var/log/confluent-control-center
        CONTROL_CENTER_OPTS: "-Djava.io.tmpdir=/var/lib/confluent-control-center/tmp"
      systemd:
        enabled: yes
        state: started
        LimitNOFILE: 128000
        TimeoutStopSec: 300
        RestartSec: 5
