schema:
  registry:
    user: cp-kafka-rest
    group: confluent
    config_file: /etc/kafka/kafka-rest.properties
    logging_config_file: /etc/kafka/kafka-rest.logging.properties
    #    systemd_file: /usr/lib/systemd/system/confluent-kafka-rest.service
    service_name: confluent-kafka-rest
    config:
      listeners: http://0.0.0.0:8081
      kafkastore.topic: _schemas
      debug: false
    environment:
      SCHEMA_REGISTRY_HEAP_OPTS: "-Xmx1000M"
      LOG_DIR: /var/log/kafka-rest
    systemd:
      enabled: yes
      state: started
      LimitNOFILE: 128000
      TimeoutStopSec: 300
      RestartSec: 5
