kafka:
  connect:
    standalone:
      config_file: /etc/kafka/connect-standalone.properties
      logging_config_file: /etc/kafka/connect-standalone.logging.properties
      #      systemd_file: /usr/lib/systemd/system/confluent-connect-standalone.service
      service_name: confluent-connect-standalone
      data_dir: /var/lib/connect-standalone
      plugin_path:
        - /usr/share/java
      environment:
        KAFKA_HEAP_OPTS: "-Xmx1000M"
        LOG_DIR: /var/log/connect-standalone
      systemd:
        enabled: yes
        state: started
        LimitNOFILE: 128000
        TimeoutStopSec: 300
        RestartSec: 5
      config:
        consumer.interceptor.classes: io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor
        producer.interceptor.classes: io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor
        internal.key.converter: org.apache.kafka.connect.json.JsonConverter
        internal.key.converter.schemas.enable: false
        internal.value.converter: org.apache.kafka.connect.json.JsonConverter
        internal.value.converter.schemas.enable: false
        offset.flush.interval.ms: 10000
        key.converter: io.confluent.connect.avro.AvroConverter
        value.converter: io.confluent.connect.avro.AvroConverter
        rest.port: 8094
